### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by PhantasmProject** [darkluar/cosmic-station#1]
No run A13 The application crashes when launched. Or should it not work yet?

**Comment by shadergz** [comment]
Hey, thanks for testing the app! A significant number of exception handlers are still incomplete; there might be something misconfigured in your environment what is causing the crashes. It's not a priority for now, but I'll investigate soon

**Comment by PhantasmProject** [comment]
> Привет, спасибо за тестирование приложения! Значительное количество обработчиков исключений все еще не завершено; Возможно, в вашей среде что-то неправильно настроено, что вызывает сбои. На данный момент это не является приоритетом, но я скоро займусь расследованием.

I just happened to come across it and decided to check it out.A13 There are no Google Play services in LibreMobileOs

**Comment by shadergz** [comment]
I updated the mechanisms, making clashes difficult to occur senselessly! Numerous errors have been fixed! Take a look at the new version; the app's development will be lengthy and extensive! And now that I'm working from 7 to 5, it's going to slow down even more :)

**Comment by omagadsamsa** [comment]
my huawei yu6 won't start

**Comment by shadergz** [comment]
> my huawei yu6 won't start

Probably your device doesn't have support for some pack of instructions like CRC hardware acceleration. I will take a look and adjust to enable non-hardware implementation if needed.

Please, for other relate problems, open another issue instead of comment in a already closed one! This will help me to track problems by the users
